version: "3.8"

services:
  # Reader DB - PostgreSQL database with pgvector for storing transferred articles
  postgres:
    image: ankane/pgvector:latest
    container_name: reader-db
    environment:
      POSTGRES_DB: reader_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Map to port 5433 externally to avoid conflicts with news-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - reader_network

  # News API - External API providing access to news articles
  # This is a reference to an external service running elsewhere
  # In a real setup, we'd use network aliases to connect to it

  # Article Transfer Service - Transfers articles from news-api to reader-db
  article-transfer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: article-transfer
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Reader DB connection
      READER_DB_HOST: postgres # Use container name within Docker network
      READER_DB_PORT: 5432 # Internal port in Docker network
      READER_DB_NAME: reader_db
      READER_DB_USER: postgres
      READER_DB_PASSWORD: postgres
      # News API connection options (will try these in order)
      NEWS_API_BASE_URL: http://news-api:8000 # Try container name first
      NEWS_API_FALLBACK_URLS: "http://host.docker.internal:8000,http://172.17.0.1:8000,http://localhost:8000"
      # Processing settings
      MAX_WORKERS: 4 # Number of parallel workers for processing
      # Gemini API settings
      GEMINI_API_KEY: ${GEMINI_API_KEY:-YOUR_API_KEY_HERE}
      GEMINI_EMBEDDING_MODEL: ${GEMINI_EMBEDDING_MODEL:-text-embedding-004}
      GEMINI_EMBEDDING_TASK_TYPE: ${GEMINI_EMBEDDING_TASK_TYPE:-CLUSTERING}
      GEMINI_EMBEDDING_INPUT_TOKEN_LIMIT: ${GEMINI_EMBEDDING_INPUT_TOKEN_LIMIT:-2048}
      GEMINI_EMBEDDING_OUTPUT_DIMENSION: ${GEMINI_EMBEDDING_OUTPUT_DIMENSION:-768}
      # Python path for Google imports
      PYTHONPATH: /app
      # Debug flag for imports
      PYTHONDEBUG: "1"
      # Add any proxy settings if needed
      # HTTP_PROXY: ${HTTP_PROXY:-}
      # HTTPS_PROXY: ${HTTPS_PROXY:-}
      # Flash model settings
      GEMINI_FLASH_MODEL: ${GEMINI_FLASH_MODEL:-gemini-2.0-flash}
      GEMINI_INPUT_CONTEXT_WINDOW_TOKEN: ${GEMINI_INPUT_CONTEXT_WINDOW_TOKEN:-1048576}
      GEMINI_FLASH_OUTPUT_WINDOW_TOKEN: ${GEMINI_FLASH_OUTPUT_WINDOW_TOKEN:-8192}
      GEMINI_FLASH_RATE_LIMIT_PER_MINUTE: ${GEMINI_FLASH_RATE_LIMIT_PER_MINUTE:-15}
      GEMINI_FLASH_RATE_LIMIT_PER_DAY: ${GEMINI_FLASH_RATE_LIMIT_PER_DAY:-1500}
      # Debugging options
      LOG_LEVEL: INFO
      # Polling interval
      POLLING_INTERVAL: 300
      WAIT_SECONDS: 10
    command: ["python", "src/main.py", "--workers", "4"]
    volumes:
      - ./src:/app/src # Mount source code for easier development
      - ./logs:/app/logs # Mount logs directory for error reports
    networks:
      - reader_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://postgres:5432')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  # pgAdmin - Web interface for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: reader-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reader.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - reader_network

  # Backend service for database setup and management
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reader-backend
    environment:
      READER_DB_HOST: postgres # Use container name within Docker network
      READER_DB_PORT: 5432 # Internal port in Docker network
      READER_DB_NAME: reader_db
      READER_DB_USER: postgres
      READER_DB_PASSWORD: postgres
      # Gemini API settings
      GEMINI_API_KEY: ${GEMINI_API_KEY:-YOUR_API_KEY_HERE}
      GEMINI_EMBEDDING_MODEL: ${GEMINI_EMBEDDING_MODEL:-text-embedding-004}
      GEMINI_EMBEDDING_TASK_TYPE: ${GEMINI_EMBEDDING_TASK_TYPE:-CLUSTERING}
      GEMINI_EMBEDDING_INPUT_TOKEN_LIMIT: ${GEMINI_EMBEDDING_INPUT_TOKEN_LIMIT:-2048}
      GEMINI_EMBEDDING_OUTPUT_DIMENSION: ${GEMINI_EMBEDDING_OUTPUT_DIMENSION:-768}
      # Python path for Google imports
      PYTHONPATH: /app
      # Debug flag for imports
      PYTHONDEBUG: "1"
      # Add any proxy settings if needed
      # HTTP_PROXY: ${HTTP_PROXY:-}
      # HTTPS_PROXY: ${HTTPS_PROXY:-}
      # Flash model settings
      GEMINI_FLASH_MODEL: ${GEMINI_FLASH_MODEL:-gemini-2.0-flash}
      GEMINI_INPUT_CONTEXT_WINDOW_TOKEN: ${GEMINI_INPUT_CONTEXT_WINDOW_TOKEN:-1048576}
      GEMINI_FLASH_OUTPUT_WINDOW_TOKEN: ${GEMINI_FLASH_OUTPUT_WINDOW_TOKEN:-8192}
      GEMINI_FLASH_RATE_LIMIT_PER_MINUTE: ${GEMINI_FLASH_RATE_LIMIT_PER_MINUTE:-15}
      GEMINI_FLASH_RATE_LIMIT_PER_DAY: ${GEMINI_FLASH_RATE_LIMIT_PER_DAY:-1500}
      WAIT_FOR_DB: "true"
      WAIT_SECONDS: "10"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src # Mount source code for easier development
    restart: unless-stopped
    networks:
      - reader_network
    command: ["python", "src/database/db_setup.py"]

  # NOTE: If you already have news-db running in another docker-compose setup,
  # you can comment out this section and just connect the existing container
  # to the reader_network using:
  # docker network connect reader_network news-db
  #
  # news-db:
  #   image: postgres:15
  #   container_name: news-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: news_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - news_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - reader_network

# Define Docker networks
networks:
  reader_network:
    driver: bridge
    name: reader_network

# Define persistent volumes
volumes:
  postgres_data: # Persistent volume for reader-db data
  # news_data:
